services:
  file-browser:
    container_name: explorer
    restart: unless-stopped
    build: . # v2.21.1
    command: sh -c "/config/startup.sh"
    environment:
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /media/multimedia/file-browser:/home
      - ./visuals:/visuals
      - ./config/filebrowser.db:/database.db
      - ./config/filebrowser.json:/.filebrowser.json
    ports:
      - 82:80
    expose:
      - 82
    security_opt:
      - no-new-privileges:true
    networks:
      - file-browser

networks:
  file-browser:
    ipam:
      driver: default